"""Enumerations that name every SEO issue, its category, and how it is graded.

Kept apart from the catalogue rows so the row table can be laid out as data
and both `catalogue` and `audit` can import these without a cycle. Domain
taxonomy enums use UPPER member names and values (CLAUDE.md ruling 3).
"""

from __future__ import annotations

from enum import StrEnum

__all__ = ["IssueCategory", "IssueId", "Priority", "Severity"]


class IssueCategory(StrEnum):
    """Client-facing grouping of issues; one workbook section per member."""

    RESPONSE_CODES_INTERNAL = "RESPONSE_CODES_INTERNAL"
    URL_ISSUES = "URL_ISSUES"
    PAGE_TITLES = "PAGE_TITLES"
    META_DESCRIPTION = "META_DESCRIPTION"
    H1 = "H1"
    CANONICALS = "CANONICALS"
    DIRECTIVES = "DIRECTIVES"
    SITEMAPS = "SITEMAPS"
    SECURITY = "SECURITY"
    PAGE_SPEED_CWV = "PAGE_SPEED_CWV"
    STRUCTURED_DATA = "STRUCTURED_DATA"
    INTERNAL_LINKS = "INTERNAL_LINKS"
    CONTENT_ISSUES = "CONTENT_ISSUES"
    CUSTOM_SEARCH = "CUSTOM_SEARCH"
    PAGINATION = "PAGINATION"
    HREFLANG_TAGS = "HREFLANG_TAGS"


class Severity(StrEnum):
    """How wrong a finding is. Declared in strictness order, strictest first."""

    ISSUE = "ISSUE"
    WARNING = "WARNING"
    OPPORTUNITY = "OPPORTUNITY"


class Priority(StrEnum):
    """How soon a finding should be acted on. Strictest first."""

    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class IssueId(StrEnum):
    """Stable identifier for every catalogue row.

    Names are category-prefixed because labels such as ``Missing`` recur across
    categories. Values equal names, matching the other domain taxonomy enums.
    """

    RESPONSE_CODES_3XX_REDIRECTION = "RESPONSE_CODES_3XX_REDIRECTION"
    RESPONSE_CODES_INTERNAL_CLIENT_ERROR_4XX = "RESPONSE_CODES_INTERNAL_CLIENT_ERROR_4XX"
    RESPONSE_CODES_INTERNAL_SERVER_ERROR_5XX = "RESPONSE_CODES_INTERNAL_SERVER_ERROR_5XX"
    RESPONSE_CODES_INTERNAL_NO_RESPONSE = "RESPONSE_CODES_INTERNAL_NO_RESPONSE"
    RESPONSE_CODES_INTERNAL_REDIRECT_CHAIN = "RESPONSE_CODES_INTERNAL_REDIRECT_CHAIN"
    RESPONSE_CODES_INTERNAL_REDIRECT_LOOP = "RESPONSE_CODES_INTERNAL_REDIRECT_LOOP"
    RESPONSE_CODES_INTERNAL_BLOCKED_BY_ROBOTS_TXT = "RESPONSE_CODES_INTERNAL_BLOCKED_BY_ROBOTS_TXT"
    URL_UPPERCASE = "URL_UPPERCASE"
    URL_UNDERSCORES = "URL_UNDERSCORES"
    URL_PARAMETERS = "URL_PARAMETERS"
    URL_MULTIPLE_SLASHES = "URL_MULTIPLE_SLASHES"
    URL_REPETITIVE_PATH = "URL_REPETITIVE_PATH"
    URL_CONTAINS_SPACE = "URL_CONTAINS_SPACE"
    PAGE_TITLES_MISSING = "PAGE_TITLES_MISSING"
    PAGE_TITLES_DUPLICATE = "PAGE_TITLES_DUPLICATE"
    PAGE_TITLES_OVER_561_PIXELS = "PAGE_TITLES_OVER_561_PIXELS"
    PAGE_TITLES_BELOW_200_PIXELS = "PAGE_TITLES_BELOW_200_PIXELS"
    PAGE_TITLES_SAME_AS_H1 = "PAGE_TITLES_SAME_AS_H1"
    PAGE_TITLES_MULTIPLE = "PAGE_TITLES_MULTIPLE"
    PAGE_TITLES_OUTSIDE_HEAD = "PAGE_TITLES_OUTSIDE_HEAD"
    META_DESCRIPTION_MISSING = "META_DESCRIPTION_MISSING"
    META_DESCRIPTION_DUPLICATE = "META_DESCRIPTION_DUPLICATE"
    META_DESCRIPTION_OVER_985_PIXELS = "META_DESCRIPTION_OVER_985_PIXELS"
    META_DESCRIPTION_BELOW_400_PIXELS = "META_DESCRIPTION_BELOW_400_PIXELS"
    META_DESCRIPTION_MULTIPLE = "META_DESCRIPTION_MULTIPLE"
    META_DESCRIPTION_OUTSIDE_HEAD = "META_DESCRIPTION_OUTSIDE_HEAD"
    H1_MISSING = "H1_MISSING"
    H1_DUPLICATE = "H1_DUPLICATE"
    H1_OVER_70_CHARACTERS = "H1_OVER_70_CHARACTERS"
    H1_MULTIPLE = "H1_MULTIPLE"
    CANONICALS_CANONICALISED = "CANONICALS_CANONICALISED"
    CANONICALS_MISSING = "CANONICALS_MISSING"
    CANONICALS_MULTIPLE = "CANONICALS_MULTIPLE"
    CANONICALS_NON_INDEXABLE_CANONICAL = "CANONICALS_NON_INDEXABLE_CANONICAL"
    CANONICALS_MULTIPLE_CONFLICTING = "CANONICALS_MULTIPLE_CONFLICTING"
    CANONICALS_CANONICAL_IS_RELATIVE = "CANONICALS_CANONICAL_IS_RELATIVE"
    CANONICALS_UNLINKED = "CANONICALS_UNLINKED"
    CANONICALS_INVALID_ATTRIBUTE_IN_ANNOTATION = "CANONICALS_INVALID_ATTRIBUTE_IN_ANNOTATION"
    CANONICALS_CONTAINS_FRAGMENT_URL = "CANONICALS_CONTAINS_FRAGMENT_URL"
    CANONICALS_OUTSIDE_HEAD = "CANONICALS_OUTSIDE_HEAD"
    DIRECTIVES_NOINDEX = "DIRECTIVES_NOINDEX"
    DIRECTIVES_NOFOLLOW = "DIRECTIVES_NOFOLLOW"
    SITEMAPS_URLS_NOT_IN_SITEMAP = "SITEMAPS_URLS_NOT_IN_SITEMAP"
    SITEMAPS_ORPHAN_URLS = "SITEMAPS_ORPHAN_URLS"
    SITEMAPS_NON_INDEXABLE_URLS_IN_SITEMAP = "SITEMAPS_NON_INDEXABLE_URLS_IN_SITEMAP"
    SITEMAPS_XML_SITEMAP_OVER_50K_URLS = "SITEMAPS_XML_SITEMAP_OVER_50K_URLS"
    SECURITY_HTTP_URLS = "SECURITY_HTTP_URLS"
    SECURITY_MIXED_CONTENT = "SECURITY_MIXED_CONTENT"
    SECURITY_FORM_URL_INSECURE = "SECURITY_FORM_URL_INSECURE"
    SECURITY_FORM_ON_HTTP_URL = "SECURITY_FORM_ON_HTTP_URL"
    SECURITY_MISSING_HSTS_HEADER = "SECURITY_MISSING_HSTS_HEADER"
    SECURITY_UNSAFE_CROSS_ORIGIN_LINKS = "SECURITY_UNSAFE_CROSS_ORIGIN_LINKS"
    SECURITY_PROTOCOL_RELATIVE_RESOURCE_LINKS = "SECURITY_PROTOCOL_RELATIVE_RESOURCE_LINKS"
    SECURITY_MISSING_CONTENT_SECURITY_POLICY_HEADER = (
        "SECURITY_MISSING_CONTENT_SECURITY_POLICY_HEADER"
    )
    SECURITY_MISSING_X_CONTENT_TYPE_OPTIONS_HEADER = (
        "SECURITY_MISSING_X_CONTENT_TYPE_OPTIONS_HEADER"
    )
    SECURITY_MISSING_X_FRAME_OPTIONS_HEADER = "SECURITY_MISSING_X_FRAME_OPTIONS_HEADER"
    SECURITY_MISSING_SECURE_REFERRER_POLICY_HEADER = (
        "SECURITY_MISSING_SECURE_REFERRER_POLICY_HEADER"
    )
    SECURITY_BAD_CONTENT_TYPE = "SECURITY_BAD_CONTENT_TYPE"
    PAGE_SPEED_LCP = "PAGE_SPEED_LCP"
    PAGE_SPEED_INP = "PAGE_SPEED_INP"
    PAGE_SPEED_CLS = "PAGE_SPEED_CLS"
    PAGE_SPEED_FCP = "PAGE_SPEED_FCP"
    PAGE_SPEED_TTFB = "PAGE_SPEED_TTFB"
    STRUCTURED_DATA_MISSING = "STRUCTURED_DATA_MISSING"
    STRUCTURED_DATA_VALIDATION_ERRORS = "STRUCTURED_DATA_VALIDATION_ERRORS"
    STRUCTURED_DATA_VALIDATION_WARNINGS = "STRUCTURED_DATA_VALIDATION_WARNINGS"
    STRUCTURED_DATA_PARSE_ERRORS = "STRUCTURED_DATA_PARSE_ERRORS"
    STRUCTURED_DATA_RICH_RESULT_VALIDATION_ERRORS = "STRUCTURED_DATA_RICH_RESULT_VALIDATION_ERRORS"
    STRUCTURED_DATA_RICH_RESULT_VALIDATION_WARNINGS = (
        "STRUCTURED_DATA_RICH_RESULT_VALIDATION_WARNINGS"
    )
    INTERNAL_LINKS_CANONICAL_ISSUE_INLINKS = "INTERNAL_LINKS_CANONICAL_ISSUE_INLINKS"
    INTERNAL_LINKS_SECURITY_HTTP_URLS_INLINKS = "INTERNAL_LINKS_SECURITY_HTTP_URLS_INLINKS"
    INTERNAL_LINKS_4XX_INLINKS = "INTERNAL_LINKS_4XX_INLINKS"
    INTERNAL_LINKS_5XX_INLINKS = "INTERNAL_LINKS_5XX_INLINKS"
    INTERNAL_LINKS_3XX_INLINKS = "INTERNAL_LINKS_3XX_INLINKS"
    INTERNAL_LINKS_NO_RESPONSE_INLINKS = "INTERNAL_LINKS_NO_RESPONSE_INLINKS"
    INTERNAL_LINKS_BLOCKED_BY_ROBOTS_TXT_INLINKS = "INTERNAL_LINKS_BLOCKED_BY_ROBOTS_TXT_INLINKS"
    INTERNAL_LINKS_BLOCKED_RESOURCE_INLINKS = "INTERNAL_LINKS_BLOCKED_RESOURCE_INLINKS"
    INTERNAL_LINKS_FUNCTIONAL_ANALYSIS = "INTERNAL_LINKS_FUNCTIONAL_ANALYSIS"
    CONTENT_LOW_CONTENT_PAGES = "CONTENT_LOW_CONTENT_PAGES"
    CONTENT_SOFT_404_PAGES = "CONTENT_SOFT_404_PAGES"
    CONTENT_SPELLING_ERRORS = "CONTENT_SPELLING_ERRORS"
    CONTENT_GRAMMAR_ERRORS = "CONTENT_GRAMMAR_ERRORS"
    CONTENT_READABILITY_DIFFICULT = "CONTENT_READABILITY_DIFFICULT"
    CONTENT_READABILITY_VERY_DIFFICULT = "CONTENT_READABILITY_VERY_DIFFICULT"
    CONTENT_LOREM_IPSUM_PLACEHOLDER = "CONTENT_LOREM_IPSUM_PLACEHOLDER"
    CONTENT_NEAR_DUPLICATES = "CONTENT_NEAR_DUPLICATES"
    CONTENT_EXACT_DUPLICATES = "CONTENT_EXACT_DUPLICATES"
    CUSTOM_SEARCH_GA4_TAGS = "CUSTOM_SEARCH_GA4_TAGS"
    CUSTOM_SEARCH_GTM_TAGS = "CUSTOM_SEARCH_GTM_TAGS"
    CUSTOM_SEARCH_OG_TAGS = "CUSTOM_SEARCH_OG_TAGS"
    CUSTOM_SEARCH_TWITTER_CARD = "CUSTOM_SEARCH_TWITTER_CARD"
    PAGINATION_URL_NOT_IN_ANCHOR_TAG = "PAGINATION_URL_NOT_IN_ANCHOR_TAG"
    PAGINATION_UNLINKED_URLS = "PAGINATION_UNLINKED_URLS"
    PAGINATION_NON_INDEXABLE = "PAGINATION_NON_INDEXABLE"
    PAGINATION_MULTIPLE_URLS = "PAGINATION_MULTIPLE_URLS"
    PAGINATION_LOOP = "PAGINATION_LOOP"
    PAGINATION_SEQUENCE_ERROR = "PAGINATION_SEQUENCE_ERROR"
    HREFLANG_NON_200_URLS = "HREFLANG_NON_200_URLS"
    HREFLANG_UNLINKED_URLS = "HREFLANG_UNLINKED_URLS"
    HREFLANG_MISSING_RETURN_LINKS = "HREFLANG_MISSING_RETURN_LINKS"
    HREFLANG_NON_CANONICAL_RETURN_LINKS = "HREFLANG_NON_CANONICAL_RETURN_LINKS"
    HREFLANG_NOINDEX_RETURN_LINKS = "HREFLANG_NOINDEX_RETURN_LINKS"
    HREFLANG_INCORRECT_LANGUAGE_REGION_CODES = "HREFLANG_INCORRECT_LANGUAGE_REGION_CODES"
    HREFLANG_MULTIPLE_ENTRIES = "HREFLANG_MULTIPLE_ENTRIES"
    HREFLANG_MISSING_SELF_REFERENCE = "HREFLANG_MISSING_SELF_REFERENCE"
    HREFLANG_INCONSISTENT_LANGUAGE_REGION_RETURN_LINKS = (
        "HREFLANG_INCONSISTENT_LANGUAGE_REGION_RETURN_LINKS"
    )
    HREFLANG_NOT_USING_CANONICAL = "HREFLANG_NOT_USING_CANONICAL"
    HREFLANG_MISSING_X_DEFAULT = "HREFLANG_MISSING_X_DEFAULT"
    HREFLANG_MISSING = "HREFLANG_MISSING"
    HREFLANG_OUTSIDE_HEAD = "HREFLANG_OUTSIDE_HEAD"
