"""`POST /jobs/import`: a finished local crawl becomes a cloud job (ADR 0034).

A factory over `ApiState`, matching `build_auth_router`, for the reason that
module gives: routes close over `state` instead of declaring a `Depends`.

This route validates, limits and translates; it decides nothing about a crawl.
Decoding, validation and the URL audit are `prepare_import`
(`src/modules/seo/page_classifier/job_import.py`); persistence is
`JobStore.import_terminal`. No external call is made anywhere on this path,
and there is no `RiskClass` wrapper: an import fetches nothing and spends
nothing, and it lands in the caller's own org only.

Admission runs cheapest-first so that a refused request costs as little as
possible: the session, then the operator's hourly bucket, then the content
type, then the process-wide import slot, and only then is the body read.
The two heavy steps, inflate-and-validate (up to ~10 s and ~1.1 GiB for the
largest local result, measured) and the store write, run on a worker thread
so they cannot stall the event loop every status poll shares.

Import memory is not counted by the ADR 0031 crawl memory budget. Concurrency
1 and the 128 MiB decompressed cap are what bound it.
"""

from __future__ import annotations

import asyncio
from datetime import UTC, datetime
from typing import TYPE_CHECKING

from fastapi import APIRouter, Header, HTTPException, Request, Response, status
from pydantic import Field

from src.api.auth import require_principal
from src.api.worker_route_helpers import read_capped_body
from src.core.bounded_gzip import DecompressedTooLargeError, InvalidGzipError
from src.core.config import get_settings
from src.core.logger import get_logger
from src.core.schemas import StrictModel
from src.core.state_store import ImportConflictError, ImportOutcome, JobStoreUnavailableError
from src.modules.seo.page_classifier.job_import import BundleInvalidError, prepare_import

if TYPE_CHECKING:
    from src.api.server import ApiState

__all__ = ["JobImportAccepted", "build_job_import_router"]

_logger = get_logger(__name__)

_GZIP_MEDIA_TYPES = frozenset({"application/gzip", "application/x-gzip"})
_HTTP_CONTENT_TOO_LARGE = 413
_HTTP_UNPROCESSABLE = 422
"""Literals: Starlette renamed both constants, and the old names warn."""


class JobImportAccepted(StrictModel):
    """What an import returns: the cloud job it created, or the one it already was."""

    id: str = Field(description="The cloud job id, generated by this server.")
    status: str = Field(description="The job's terminal status: succeeded or partial.")
    label: str = Field(description="The job's label.")
    pages: int = Field(ge=0, description="Pages in the imported result.")
    duplicate: bool = Field(description="True when this exact bundle was already imported.")


def build_job_import_router(state: ApiState) -> APIRouter:
    """Build the import route over `state`."""
    router = APIRouter()

    @router.post("/jobs/import", response_model=JobImportAccepted, status_code=201)
    async def import_job(
        request: Request,
        response: Response,
        authorization: str | None = Header(default=None),
        content_type: str | None = Header(default=None),
    ) -> JobImportAccepted:
        """Store a finished local crawl as a terminal job in the caller's org.

        The body is the gzip of a `JobImportBundle`'s JSON, sent as
        `application/gzip`. Nothing in it can name an org, an operator or a
        job id: the org and operator come from the session, and the id from
        the store.

        Safe to retry with the same bytes: an identical bundle for a source
        job already imported into this org returns `200` and that job, with
        `duplicate: true`.

        Raises:
            HTTPException: `401` no valid session; `429` the operator's hourly
                import allowance is spent, or another import is running;
                `415` not gzip; `413` over the compressed or decompressed cap;
                `400` malformed gzip; `422` the bundle fails the contract or
                the URL audit (locations only, never values); `409` this
                source job was imported here with different content, or the
                org is not provisioned; `503` the job database is unavailable.
        """
        principal = require_principal(authorization, session_secret=state.session_secret)
        settings = get_settings()
        bucket = state.principal_rate_limiter.get_or_create_per_hour(
            f"import:{principal.operator_id}",
            settings.job_import_per_hour,
            settings.job_import_burst,
        )
        if not bucket.try_acquire():
            _logger.warning("job_import_rate_limited", extra={"operator_id": principal.operator_id})
            raise HTTPException(
                status.HTTP_429_TOO_MANY_REQUESTS,
                detail="import limit reached for this operator; try again later",
            )

        media_type = (content_type or "").split(";", 1)[0].strip().lower()
        if media_type not in _GZIP_MEDIA_TYPES:
            raise HTTPException(
                status.HTTP_415_UNSUPPORTED_MEDIA_TYPE,
                detail="send the bundle gzipped, as application/gzip",
            )

        if not state.import_lock.acquire(blocking=False):
            raise HTTPException(
                status.HTTP_429_TOO_MANY_REQUESTS,
                detail="another import is running on this server; try again in a minute",
            )
        try:
            body = await read_capped_body(
                request,
                max_bytes=settings.job_import_max_compressed_bytes,
                log_prefix="job_import",
            )
            outcome, prepared_pages, decompressed = await asyncio.to_thread(
                _prepare_and_store,
                state,
                body,
                settings.job_import_max_decompressed_bytes,
                principal.org_id,
                principal.operator_id,
            )
        finally:
            state.import_lock.release()

        record = outcome.record
        provenance = record.provenance
        _logger.info(
            "job_imported",
            extra={
                "operator_id": principal.operator_id,
                "org": principal.org_id,
                "job_id": record.id,
                "duplicate": outcome.duplicate,
                "source_instance_id": provenance.source_instance_id if provenance else None,
                "source_job_id": provenance.source_job_id if provenance else None,
                "bundle_sha256": provenance.bundle_sha256 if provenance else None,
                "compressed_bytes": len(body),
                "decompressed_bytes": decompressed,
                "pages": prepared_pages,
            },
        )
        if outcome.duplicate:
            response.status_code = status.HTTP_200_OK
        return JobImportAccepted(
            id=record.id,
            status=record.status.value,
            label=record.label,
            pages=prepared_pages,
            duplicate=outcome.duplicate,
        )

    return router


def _prepare_and_store(
    state: ApiState, body: bytes, max_decompressed: int, org_id: str, operator_id: str
) -> tuple[ImportOutcome, int, int]:
    """Validate then persist, on a worker thread. Maps domain errors onto HTTP ones.

    The validated bundle is local to `prepare_import`, so it is released
    before the store write begins; only the re-serialised result survives.
    """
    try:
        prepared = prepare_import(
            body,
            max_decompressed=max_decompressed,
            org_id=org_id,
            operator_id=operator_id,
            now=datetime.now(UTC),
        )
    except DecompressedTooLargeError as exc:
        raise HTTPException(_HTTP_CONTENT_TOO_LARGE, detail=str(exc)) from None
    except InvalidGzipError as exc:
        raise HTTPException(status.HTTP_400_BAD_REQUEST, detail=str(exc)) from None
    except BundleInvalidError as exc:
        _logger.warning(
            "job_import_invalid",
            extra={"operator_id": operator_id, "org": org_id, "errors": exc.error_count},
        )
        raise HTTPException(
            _HTTP_UNPROCESSABLE,
            detail={
                "error": "the bundle failed validation",
                "error_count": exc.error_count,
                "locations": exc.locations,
            },
        ) from None

    try:
        outcome = state.store.import_terminal(prepared.job, prepared.result_json)
    except ImportConflictError as exc:
        raise HTTPException(
            status.HTTP_409_CONFLICT,
            detail=(
                f"this local job was already imported as {exc.existing_id} with different "
                "content; it was not imported again"
            ),
        ) from None
    except JobStoreUnavailableError as exc:
        raise HTTPException(status.HTTP_503_SERVICE_UNAVAILABLE, detail=str(exc)) from None
    except ValueError as exc:
        raise HTTPException(status.HTTP_409_CONFLICT, detail=str(exc)) from None
    return outcome, prepared.page_count, prepared.decompressed_bytes
