"""Durable job records for work that outlives the request that started it.

A 20k-page crawl takes minutes. Nothing that long can run inside an HTTP
request, so the request that *starts* a crawl and the request that *reads* its
result are different requests, in different connections, possibly on different
sides of a process restart. This module is what they share.

Domain-agnostic, deliberately
-----------------------------
`core/` must not import from `modules/` (CLAUDE.md §1). So this store knows
nothing about crawls, pages or classification: a job carries an opaque
`request` mapping in and an opaque `result` mapping out, and the caller that
owns the domain types validates them at its own boundary. The alternative —
typing `JobRecord.result` as `PageClassificationOutput` — would be a
`core -> modules` import and a build failure.

That constraint is also the right design. The same store will hold PPC and
research jobs without modification.

Metadata and results are stored separately. A finished 20k-page result is
roughly 16 MB; listing jobs must not read it, or the job list becomes the most
expensive endpoint in the system.

Durability
----------
Every write goes to a temporary file and is then moved into place with
`os.replace`, which is atomic. A process killed mid-write leaves either the
previous record or the new one, never a half-written record that fails to parse
and takes the job with it.

`recover_orphans()` closes the other half of the same problem: a job that was
`RUNNING` when the process died has no one running it any more, and would
otherwise be polled forever by a UI waiting for it to finish.
"""

from __future__ import annotations

import json
import os
import tempfile
import threading
import uuid
from collections.abc import Mapping
from datetime import UTC, datetime
from enum import StrEnum
from pathlib import Path
from typing import Protocol

from pydantic import Field

from src.core.logger import get_logger
from src.core.schemas import StrictModel

__all__ = [
    "DiskJobStore",
    "JobNotFoundError",
    "JobRecord",
    "JobStatus",
    "JobStore",
]

_logger = get_logger("core.state_store")


class JobStatus(StrEnum):
    """Lifecycle of a background job.

    Lowercase values, matching the other governance enums (CLAUDE.md §7 ruling
    3) and the `JobStatus` union the frontend already declares.
    """

    QUEUED = "queued"
    """Accepted and persisted, not yet picked up by a worker."""

    RUNNING = "running"
    """A worker is executing it now."""

    SUCCEEDED = "succeeded"
    """Finished, with a complete result."""

    PARTIAL = "partial"
    """Finished, but the result is incomplete — a crawl that hit its ceiling.

    Distinct from `SUCCEEDED` because the caller must be able to tell that what
    it is looking at is not the whole site. Presenting a truncated crawl as a
    complete one is how an audit reaches a confident wrong conclusion.
    """

    FAILED = "failed"
    """Did not produce a result. `error` says why."""


TERMINAL_STATUSES = frozenset({JobStatus.SUCCEEDED, JobStatus.PARTIAL, JobStatus.FAILED})
"""Statuses from which a job never moves again, so a poller can stop."""


class JobNotFoundError(KeyError):
    """No job exists with the given id."""


class JobRecord(StrictModel):
    """Metadata for one background job. Small enough to list cheaply.

    Attributes:
        id: Opaque identifier. Generated by the store, never by a client — a
            client-supplied id is a path-traversal parameter.
        tool_name: Which tool this job runs, e.g. `seo.page_classifier`.
        label: Human-facing description, shown in a job list.
        request: The tool's input payload, serialised. Opaque here; the API
            layer validates it back into a typed model.
        status: Current lifecycle state.
        created_at: When the job was accepted.
        updated_at: When the status last changed.
        started_at: When a worker picked it up.
        finished_at: When it reached a terminal status.
        error: Failure reason. Set only for `FAILED`.
        has_result: Whether a result blob exists to fetch.
    """

    id: str = Field(min_length=1)
    tool_name: str = Field(min_length=1)
    label: str = ""
    request: Mapping[str, object] = Field(default_factory=dict)
    status: JobStatus = JobStatus.QUEUED
    created_at: datetime
    updated_at: datetime
    started_at: datetime | None = None
    finished_at: datetime | None = None
    error: str | None = None
    has_result: bool = False

    @property
    def is_terminal(self) -> bool:
        """Whether the job has reached a state it will never leave."""
        return self.status in TERMINAL_STATUSES


class JobStore(Protocol):
    """The persistence seam.

    A Protocol so the hosted deployment (ADR 0004) can drop in a shared
    implementation — Redis, Postgres — without the API layer changing. The disk
    implementation below is correct for a single local process and explicitly
    not for several (see `DiskJobStore`).
    """

    def create(self, tool_name: str, request: Mapping[str, object], label: str = "") -> JobRecord:
        """Persist a new job in `QUEUED` and return it."""
        ...

    def get(self, job_id: str) -> JobRecord:
        """Read one job's metadata."""
        ...

    def list_jobs(self) -> list[JobRecord]:
        """Every job, newest first. Metadata only."""
        ...

    def mark_running(self, job_id: str) -> JobRecord:
        """Move a job to `RUNNING`."""
        ...

    def mark_failed(self, job_id: str, error: str) -> JobRecord:
        """Move a job to `FAILED` with a reason."""
        ...

    def finish(
        self, job_id: str, result: Mapping[str, object], *, partial: bool = False
    ) -> JobRecord:
        """Store a result and move the job to a terminal success state."""
        ...

    def read_result(self, job_id: str) -> Mapping[str, object]:
        """Read a job's result blob."""
        ...

    def recover_orphans(self) -> list[str]:
        """Fail every job left non-terminal by a previous process."""
        ...


def _now() -> datetime:
    return datetime.now(UTC)


def _atomic_write(path: Path, payload: str) -> None:
    """Write `payload` to `path` so that a crash cannot leave it half-written.

    The temporary file is created in the destination directory rather than the
    system temp dir: `os.replace` is only atomic within a filesystem, and on
    Windows it fails outright across volumes.
    """
    handle, temporary = tempfile.mkstemp(dir=str(path.parent), suffix=".tmp")
    try:
        with os.fdopen(handle, "w", encoding="utf-8") as stream:
            stream.write(payload)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, path)
    except BaseException:
        Path(temporary).unlink(missing_ok=True)
        raise


class DiskJobStore:
    """A `JobStore` backed by one JSON file per job under a single directory.

    Single-process only. The lock is a `threading.Lock`, which serialises the
    API's event loop against its worker threads but does nothing across
    processes — two servers sharing a directory would interleave writes. That is
    the same in-process limitation the rate limiter and cost ledger carry
    (CLAUDE.md §8), and it is acceptable for the same reason: ADR 0004 targets a
    single local workstation.
    """

    def __init__(self, root: Path | str) -> None:
        """Create the store, making its directory if absent.

        Args:
            root: Directory to hold job files. Created if it does not exist.
        """
        self._root = Path(root)
        self._root.mkdir(parents=True, exist_ok=True)
        self._lock = threading.Lock()

    @property
    def root(self) -> Path:
        """Directory holding the job files."""
        return self._root

    def _record_path(self, job_id: str) -> Path:
        return self._root / f"{job_id}.json"

    def _result_path(self, job_id: str) -> Path:
        return self._root / f"{job_id}.result.json"

    def _read(self, job_id: str) -> JobRecord:
        path = self._record_path(job_id)
        if not path.exists():
            msg = f"no job with id {job_id!r}"
            raise JobNotFoundError(msg)
        return JobRecord.model_validate_json(path.read_text(encoding="utf-8"))

    def _write(self, record: JobRecord) -> None:
        _atomic_write(self._record_path(record.id), record.model_dump_json())

    def create(self, tool_name: str, request: Mapping[str, object], label: str = "") -> JobRecord:
        """Persist a new job in `QUEUED`.

        The id is generated here rather than accepted from the caller. Every id
        becomes a filename, so a caller-supplied one is a path-traversal
        parameter — `../../etc/passwd` would be a valid "job id".

        Args:
            tool_name: Which tool the job runs.
            request: The tool's serialised input payload.
            label: Human-facing description for a job list.

        Returns:
            The persisted record.
        """
        moment = _now()
        record = JobRecord(
            id=uuid.uuid4().hex,
            tool_name=tool_name,
            label=label,
            request=dict(request),
            status=JobStatus.QUEUED,
            created_at=moment,
            updated_at=moment,
        )
        with self._lock:
            self._write(record)
        _logger.info("job_created", extra={"job_id": record.id, "tool": tool_name})
        return record

    def get(self, job_id: str) -> JobRecord:
        """Read one job's metadata.

        Raises:
            JobNotFoundError: If no such job exists.
        """
        with self._lock:
            return self._read(job_id)

    def list_jobs(self) -> list[JobRecord]:
        """Every job, newest first.

        Reads metadata only, never result blobs. A record that fails to parse is
        skipped rather than raised: one corrupt file must not make the job list
        permanently unavailable.
        """
        records: list[JobRecord] = []
        with self._lock:
            for path in self._root.glob("*.json"):
                if path.name.endswith(".result.json"):
                    continue
                try:
                    records.append(JobRecord.model_validate_json(path.read_text(encoding="utf-8")))
                except (ValueError, OSError) as exc:
                    _logger.warning(
                        "job_record_unreadable", extra={"path": path.name, "error": str(exc)}
                    )
        return sorted(records, key=lambda record: record.created_at, reverse=True)

    def _transition(self, job_id: str, **changes: object) -> JobRecord:
        """Apply a status change under the lock, so no update is lost."""
        with self._lock:
            record = self._read(job_id)
            updated = record.model_copy(update={**changes, "updated_at": _now()})
            self._write(updated)
        return updated

    def mark_running(self, job_id: str) -> JobRecord:
        """Move a job to `RUNNING` and stamp its start time."""
        return self._transition(job_id, status=JobStatus.RUNNING, started_at=_now())

    def mark_failed(self, job_id: str, error: str) -> JobRecord:
        """Move a job to `FAILED` with a reason.

        Args:
            job_id: The job.
            error: Operator-facing reason. Must say something; a failed job with
                a blank reason is indistinguishable from a bug in the store.
        """
        return self._transition(
            job_id, status=JobStatus.FAILED, error=error or "unknown error", finished_at=_now()
        )

    def finish(
        self, job_id: str, result: Mapping[str, object], *, partial: bool = False
    ) -> JobRecord:
        """Store a result blob and move the job to a terminal success state.

        The blob is written **before** the metadata. A reader only learns a
        result exists by seeing `has_result` on the record, so writing in this
        order means a crash between the two writes leaves a job that still looks
        unfinished — recoverable — rather than one that advertises a result
        which is not there.

        Args:
            job_id: The job.
            result: The tool's serialised output.
            partial: True when the result is incomplete, e.g. a crawl that hit
                its page ceiling.

        Returns:
            The updated record.
        """
        with self._lock:
            self._read(job_id)  # Fail before writing a blob for a job that is gone.
            _atomic_write(self._result_path(job_id), json.dumps(dict(result)))

        status = JobStatus.PARTIAL if partial else JobStatus.SUCCEEDED
        record = self._transition(job_id, status=status, has_result=True, finished_at=_now())
        _logger.info("job_finished", extra={"job_id": job_id, "status": status.value})
        return record

    def read_result(self, job_id: str) -> Mapping[str, object]:
        """Read a job's result blob.

        Raises:
            JobNotFoundError: If the job or its result does not exist.
        """
        path = self._result_path(job_id)
        with self._lock:
            self._read(job_id)
            if not path.exists():
                msg = f"job {job_id!r} has no result"
                raise JobNotFoundError(msg)
            loaded: Mapping[str, object] = json.loads(path.read_text(encoding="utf-8"))
        return loaded

    def recover_orphans(self) -> list[str]:
        """Fail every job left non-terminal by a previous process.

        Call once at startup. A job that was `RUNNING` when the process died has
        no worker any more, and nothing will ever move it: a UI polling it would
        wait for a result that is never coming. Marking it `FAILED` is honest —
        the work really was lost, because there is no crawl checkpointing
        (CLAUDE.md §8) to resume from.

        Returns:
            The ids that were failed.
        """
        recovered: list[str] = []
        for record in self.list_jobs():
            if record.is_terminal:
                continue
            self.mark_failed(record.id, "interrupted by a server restart")
            recovered.append(record.id)

        if recovered:
            _logger.warning("orphaned_jobs_recovered", extra={"count": len(recovered)})
        return recovered
